### PR TITLE
Feature/15.0/batch report printing

### PR DESCRIPTION
**Pull request by ambientstl**
[Batch report printing [19851]](https://erp.bluestingray.com/web#id=19851&view_type=form&model=project.task&action=378&menu_id=263)

[BLUE-3][ADD] New module: Batch Report Printing
    
From: [OCA Batch Report Printing](https://github.com/OCA/reporting-engine/tree/13.0/report_batch)
For: [BLUE-3] Batch report printing

[BLUE-3][UPD] Batch report printing customizations
    
Changes:
     - Adds a new Server Action, Batch Print Reports, for Sale Order and Product Template models
     - Adds a new wizard, Batch Print Report Wizard, that is launched by the Server Action
       - All HTML reports for the model are available for batching
       - Adds the option to collate reports by record instead of report
     - Adds a handful of placeholder Sale Order reports (to be removed)
    
Missing features (I think this most of these need to be addressed in JS):
     - Batch report opens in new tab
     - Batch report displays without top nav bar
     - Batch report has a customizable, non-printing header
       - I added the supplied header HTML to the top of the report, but it makes all reports editable

### CODE REVIEW

**Comment by ambientstl** [comment]
Leaving this in draft for now since it still missing some pieces, but I think almost all of the needed functionality is there.

**Comment by traviswaelbro** [comment]
@ambientstl do you want this reviewed or anything in the current state?

**Comment by traviswaelbro** [comment]
> @ambientstl do you want this reviewed or anything in the current state?

@ambientstl bump

**Comment by ambientstl** [comment]
@traviswaelbro I think this can be closed since we have the PR on our `reporting-engine` fork

**Pull request closed without merging**
